### ISSUE TITLE
Whats your discord

### ISSUE THREAD

**Issue by ferper04** [SpikeHD/nds_pong#1]
Bro i need to contact you with some funny thing

**Comment by SpikeHD** [comment]
If it's important just put it [here](https://github.com/SpikeHD/SpikeHD/issues/new)

**Comment by ferper04** [comment]
> If it's important just put it [here](https://github.com/SpikeHD/SpikeHD/issues/new)

nah but like its not too important but u will find it kinda funny trust me

**Comment by ferper04** [comment]
ok well watch this video (you are included in it)
https://youtu.be/QE4vceaPOp4

**Comment by SpikeHD** [comment]
Ah, cool to see that video inspired other people :)
